# Generated by Django 3.2.3 on 2021-11-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211109_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
    ]
